{"zhuyejiekou": [
{"name":"心爱影视(推荐)","url":"https://xays6677.com/mogai_api.php/v1.vod"},
{"name":"手指影视(推荐)","url":"https://szys5678.com/mogai_api.php/v1.vod"},
{"name":"影视达人","url":"http://www.ysdr.vip/api.php/v1.vod"},
{"name":"奈飞迷","url":"https://app.netflixmi.com/api.php/v1.vod"},
{"name":"益达影院（猴子电影）","url":"http://luobu.yss6080.com/mogai_api.php/v1.vod"},
{"name":"手指影视（老白专线）","url":"https://szys5678.com/mogai_api.php/v1.vod"},
{"name":"独播社","url":"http://35ys.cc/api.php/v1.vod"},
{"name":"饭团影视","url": "http://television.wkfile.com/api.php/app/"},
{"name":"天空影视","url":"https://www.tkys.tv/xgapp.php/v2/"},
{"name":"超人影院","url":"http://chaorenbb.com/api.php/v1.vod"},
{"name":"迪迪影院","url":"http://dd88.icu:6080/xgapp.php/v2/"},
{"name":"心爱影视","url":"https://xays6677.com/mogai_api.php/v1.vod"},
{"name":"追剧吧","url":"http://zhuiju8.vip/api.php/v1.vod"},
{"name":"快云影音","url":"https://www.kuaiyunyy.com/api.php/app/"},
{"name":"4K影院","url":"http://1api.4kdytv.com/api.php/v1.vod"},
{"name":"初心影视","url":"https://www.18mv.club/api.php/v1.vod"},
{"name":"月色影视","url":"http://69ty.cc/mogai_api.php/v1.vod"},
{"name":"蜜蜂影视","url":"http://app.f8tp.com/lvdou_api.php/v1.vod"},
{"name":"阿里影视","url":"http://aliys.cn:90/api.php/v1.vod"},
{"name":"美剧虫","url":"https://meijuchong.com/api.php/v1.vod"},
{"name":"月儿影视","url":"https://yue52.xyz/api.php/v1.vod"},
{"name":"樱花动漫","url":"https://www.dmwu.cc/api.php/v1.vod"},
{"name":"QC影视","url":"https://www.qcsvip.com/mogai_api.php/v1.vod"},
{"name":"U5影视","url":"https://appx.uy07.com/api.php/v1.vod"},
{"name":"爱影视","url":"https://www.hzlff.cn/api.php/v1.vod"},
{"name":"比邻影视","url":"http://0hzy.cn:9990/mogai_api.php/v1.vod"},
{"name":"黄河影视","url":"http://i.ledu8.cn/api.php/v1.vod"},
{"name":"极酷视频","url":"https://jiku.vip/mogai_api.php/v1.vod"},
{"name":"冷视TV","url":"https://len.tv/api.php/v1.vod"},
{"name":"橘子影视","url":"http://jz.juzidy.vip/mogai_api.php/v1.vod"},
{"name":"看剧吧","url":"http://app.ishen520.com/api.php/v1.vod"},
{"name":"看看剧","url":"https://www.kankanju.cn/api.php/v1.vod"},
{"name":"绿豆视频","url":"https://v.lvdoui.cn/mogai_api.php/v1.vod"},
{"name":"蓝光视频","url":"http://vip.91iqiyi.com/mogai_api.php/v1.vod"},
{"name":"皮皮动漫","url":"http://dm.muying.me/mogai_api.php/v1.vod"},
{"name":"天天视频","url":"http://app.qianju.cc/api.php/v1.vod"},
{"name":"小蜻蜓","url":"http://3ketv.com/mogai_api.php/v1.vod"},
{"name":"猪猪影院","url":"http://app.2zdyy.com/api.php/v1.vod"},
{"name":"播放呀","url":"https://www.bofangya.com/xgapp.php/v1/"},
{"name":"海胆影视","url":"http://xf123.cc/api.php/app/"},
{"name":"抹茶猪","url":"https://www.mczdyw.com/api.php/app/"},
{"name":"暖光影视","url":"https://app.bl210.com/api.php/v1.vod"}],
"zhujiexi":" https://json.hfyrw.com/mao.go?url=#https://jx.xmflv.com/?url=#http://47.100.138.210:91/home/api?type=ys&uid=7593435&key=ehortuyAHMNQTWX457&url=#https://jx.sujx.top/jiexi.php/?url=#https://z1.m1907.cn/?jx=#https://jx.m3u8.tv/jiexi/?url=#https://ckmov.ccyjjd.com/ckmov/?url=#https://jx.youyitv.com/?url=#https://jsap.attakids.com/?url=#https://vip.parwix.com:4433/player/?url=#https://www.yemu.xyz/?url=#https://www.pangujiexi.cc/jiexi.php?url=#https://www.gai4.com/?url=",
"beiyongjiexi": "https://jx.xmflv.com/?url=#http://api.diliktv.xyz/vip/jx.php?url=#https://nbjx.vip/?url=#https://jx.blbo.cc:4433/?url=#http://47.100.138.210:92/?url=#https://jx.parwix.com:4433/player/?url=#https://www.nxflv.com/?url=",
"dianshizhibo": "https://gitee.com/dongji2/biubiu/raw/master/tv/live.php",
"caijizhan": "http://xiaomaomi.cc/api.php",
"tiyuzhibo": "https://m.zhibo8.net",
"reci": "https://v.sogou.com",
"wuqu": "aHR0cDovL3d3dy5kanV1LmNvbQ==",
"gongju": "aHR0cDovLzQyLjE5My41NS4yNDI=",
"lunbofanye": "https://www.douyu.com/gapi/rkc/directory/mixList/2_208/",
"lunboqianzhui": "https://m.douyu.com",
"Home": {
"dy": {
"class": "全部$&class=#喜剧$&class=喜剧#爱情$&class=爱情#动作$&class=动作#枪战$&class=枪战#犯罪$&class=犯罪#惊悚$&class=惊悚#恐怖$&class=恐怖#悬疑$&class=悬疑#动画$&class=动画#家庭$&class=家庭#奇幻$&class=奇幻#魔幻$&class=魔幻#科幻$&class=科幻#战争$&class=战争#青春$&class=青春#剧情$&class=剧情#西部$&class=西部#纪录$&class=记录#音乐$&class=音乐#歌舞$&class=歌舞#运动$&class=运动#历史$&class=历史#武侠$&class=武侠#冒险$&class=冒险#传记$&class=传记",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#欧洲$&area=欧洲#韩国$&area=韩国#日本$&area=日本#泰国$&area=泰国#印度$&area=印度#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"dsj": {
"class": "全部$&class=#古装$&class=古装#言情$&class=言情#武侠$&class=武侠#偶像$&class=偶像#家庭$&class=家庭#青春$&class=青春#都市$&class=都市#喜剧$&class=喜剧#战争$&class=战争#军旅$&class=军旅#谍战$&class=谍战#悬疑$&class=悬疑#罪案$&class=罪案#穿越$&class=穿越#宫廷$&class=宫廷#历史$&class=历史#神话$&class=神话#科幻$&class=科幻#年代$&class=年代#农村$&class=农村#商战$&class=商战#剧情$&class=剧情#奇幻$&class=奇幻",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#英国$&area=英国#韩国$&area=韩国#日本$&area=日本#泰国$&area=泰国#台湾$&area=台湾#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"zy": {
"class": "全部$&class=#表演$&class=表演#播报$&class=播报#访谈$&class=访谈#体验$&class=体验#养成$&class=养成#游戏$&class=游戏#亲子$&class=亲子#美食$&class=美食#情感$&class=情感#选秀$&class=选秀#益智$&class=益智#晚会$&class=晚会#音乐$&class=音乐#文化$&class=文化#喜剧$&class=喜剧#曲艺$&class=曲艺#职场$&class=职场#脱口秀$&class=脱口秀#真人秀$&class=真人秀#竞技$&class=竞技#体育$&class=体育#萌宠$&class=萌宠",
"area": "全部$&area=#内地$&area=内地#香港$&area=香港#美国$&area=美国#韩国$&area=韩国#日本$&area=日本#台湾$&area=台湾",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
},
"dm": {
"class": "全部$&class=#搞笑$&class=搞笑#番剧$&class=番剧#国创$&class=国创#大电影$&class=大电影#热血$&class=热血#催泪$&class=催泪#治愈$&class=治愈#励志$&class=励志#机战$&class=机战#战斗$&class=战斗#恋爱$&class=恋爱#科幻$&class=科幻#奇幻$&class=奇幻#魔幻$&class=魔幻#推理$&class=推理#校园$&class=校园#日常$&class=日常#经典$&class=经典#历史$&class=历史#美食$&class=美食#职场$&class=职场#偶像$&class=偶像#泡面$&class=泡面#冒险$&class=冒险#竞技$&class=竞技#武侠$&class=武侠#玄幻$&class=玄幻",
"area": "全部$&area=#内地$&area=内地#日本$&area=日本#欧美$&area=欧美#其它$&area=其它",
"year": "全部$&lang=&year=#2022$&lang=&year=2022#2021$&lang=&year=2021#2020$&lang=&year=2020#2019$&lang=&year=2019#2018$&lang=&year=2018#2017$&lang=&year=2017#2016-2011$&lang=&year=2016#2010-2000$&lang=&year=2010#90年代$&lang=&year=90#80年代$&lang=&year=80#更早$&lang=&year=70"
}
},
"zidingyi":  {"name": "乐猪影视",
"url": "http://www.lezhutv.com",
"tihuan": "cnzz.com",
"User": "空",
"fenlei": "电视剧$/type/2-#电影$/type/1-#综艺$/type/3-#动漫$/type/4-#韩剧$/type/14-#美剧$/type/15-",
"houzhui": ".html",
"shifouercijiequ": "0",
"jiequqian": "空",
"jiequhou": "空",
"jiequshuzuqian": "class=\"vbox\"",
"jiequshuzuhou": "</a>",
"tupianqian": "data-original=\"",
"tupianhou": "\"",
"biaotiqian": "title=\"",
"biaotihou": "\"",
"lianjieqian": "href=\"",
"lianjiehou": "\"",
"sousuoqian": "/search-pg-1-wd-",
"sousuohou": ".html",
"sousuohouzhui": "/detail/",
"ssmoshi": "1",
"sousuoshifouercijiequ": "0",
"jspic": "空",
"jsname": "空",
"jsid": "空",
"ssjiequqian": "空",
"ssjiequhou": "空",
"ssjiequshuzuqian": "class=\"vbox\"",
"ssjiequshuzuhou": "</a>",
"sstupianqian": "data-original=\"",
"sstupianhou": "\"",
"ssbiaotiqian": "title=\"",
"ssbiaotihou": "\"",
"sslianjieqian": "href=\"",
"sslianjiehou": "\"",
"bfshifouercijiequ": "0",
"bfjiequqian": "空",
"bfjiequhou": "空",
"bfjiequshuzuqian": "class=\"list_block show\"",
"bfjiequshuzuhou": "</ul>",
"zhuangtaiqian": "class=\"yac\"",
"zhuangtaihou": "</p>",
"daoyanqian": "导演：</span>",
"daoyanhou": "</p>",
"zhuyanqian": "主演：</span>",
"zhuyanhou": "</p>",
"juqingqian": "class=\"tbox_js\">",
"juqinghou": "</div>",
"bfyshifouercijiequ": "0",
"bfyjiequqian": "空",
"bfyjiequhou": "空",
"bfyjiequshuzuqian": "<li>",
"bfyjiequshuzuhou": "</li>",
"bfbiaotiqian": "\">",
"bfbiaotihou": "</a>",
"bflianjieqian": "href=\"",
"bflianjiehou": "\""}}
